export POSTGRES_VERSION=13.3
export POSTGRES_CONTAINER_NAME=snb-umbra
export POSTGRES_PASSWORD=mysecretpassword
export POSTGRES_DATABASE=ldbcsnb
export POSTGRES_SHARED_MEMORY=8g
export POSTGRES_USER=postgres
